# Generated by Django 4.1.7 on 2023-03-18 16:39

from django.db import migrations, models
import django.db.models.deletion
import task1.models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_alter_color_name_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Department',
            field=models.ForeignKey(default=task1.models.get_default_department, on_delete=django.db.models.deletion.CASCADE, to='task1.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='favorite_color',
            field=models.ForeignKey(default=task1.models.get_default_color, on_delete=django.db.models.deletion.CASCADE, to='task1.color'),
        ),
    ]
